language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python ./patchalerts/scanner.py --update
- coverage run ./patchalerts/scanner.py --test
after_success:
- COVERALLS_PARALLEL=true coveralls
notifications:
  email:
    on_success: never
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always
cache: pip
